package com.jumper.entity;
// Generated 2016-4-7 20:04:10 by Hibernate Tools 3.4.0.CR1

import java.util.Arrays;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TFacility generated by hbm2java
 */
@Entity
@Table(name = "t_facility", catalog = "lims")
public class TFacility implements java.io.Serializable {

	private Integer id;
	private String facid;
	private String name;
	private String productor;
	private String type;
	private String director;
	private Date buydate;
	private Integer num;
	private double price;
	private String location;
	private int state;
	private String remark;
	private byte[] image;
	private String userId;
	private String reserve;

	public TFacility() {
	}

	public TFacility(String facid, String name, String productor, String director, Date buydate, double price,
			String location, int state) {
		this.facid = facid;
		this.name = name;
		this.productor = productor;
		this.director = director;
		this.buydate = buydate;
		this.price = price;
		this.location = location;
		this.state = state;
	}

	public TFacility(String facid, String name, String productor, String type, String director, Date buydate,
			Integer num, double price, String location, int state, String remark, byte[] image, String userId,
			String reserve) {
		this.facid = facid;
		this.name = name;
		this.productor = productor;
		this.type = type;
		this.director = director;
		this.buydate = buydate;
		this.num = num;
		this.price = price;
		this.location = location;
		this.state = state;
		this.remark = remark;
		this.image = image;
		this.userId = userId;
		this.reserve = reserve;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "facid", nullable = false, length = 20)
	public String getFacid() {
		return this.facid;
	}

	public void setFacid(String facid) {
		this.facid = facid;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "productor")
	public String getProductor() {
		return this.productor;
	}

	public void setProductor(String productor) {
		this.productor = productor;
	}

	@Column(name = "type")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "director", nullable = false)
	public String getDirector() {
		return this.director;
	}

	public void setDirector(String director) {
		this.director = director;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "buydate", length = 19)
	public Date getBuydate() {
		return this.buydate;
	}

	public void setBuydate(Date buydate) {
		this.buydate = buydate;
	}

	@Column(name = "num")
	public Integer getNum() {
		return this.num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	@Column(name = "price", precision = 10, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "location", nullable = false)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "state")
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "image")
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	@Column(name = "user_id")
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "reserve")
	public String getReserve() {
		return this.reserve;
	}

	public void setReserve(String reserve) {
		this.reserve = reserve;
	}

	@Override
	public String toString() {
		return "TFacility [id=" + id + ", facid=" + facid + ", name=" + name + ", productor=" + productor + ", type="
				+ type + ", director=" + director + ", buydate=" + buydate + ", num=" + num + ", price=" + price
				+ ", location=" + location + ", state=" + state + ", remark=" + remark + ", image="
				+ Arrays.toString(image) + ", userId=" + userId + ", reserve=" + reserve + "]";
	}

	
	
}
