package com.jumper.entity;
// Generated 2016-4-7 16:37:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TOrder generated by hbm2java
 */
@Entity
@Table(name = "t_order", catalog = "lims")
public class TOrder implements java.io.Serializable {

	private Integer id;
	private String userId;
	private String classid;
	private String facilityId;
	private Integer classtime;
	private Integer num;
	private Date date;
	private Integer state;
	private String remark;

	public TOrder() {
	}

	public TOrder(Integer id, String userId, String classid, String facilityId, Integer classtime, Integer num, Date date,
			Integer state, String remark) {
		super();
		this.id = id;
		this.userId = userId;
		this.classid = classid;
		this.facilityId = facilityId;
		this.classtime = classtime;
		this.num = num;
		this.date = date;
		this.state = state;
		this.remark = remark;
	}


	@Id
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "userid", nullable = false)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "classid")	
	public String getClassid() {
		return classid;
	}

	public void setClassid(String classid) {
		this.classid = classid;
	}
	
	@Column(name = "facilityid")
	public String getFacilityId() {
		return this.facilityId;
	}

	public void setFacilityId(String facilityId) {
		this.facilityId = facilityId;
	}

	@Column(name = "classtime")
	public Integer getClasstime() {
		return this.classtime;
	}

	public void setClasstime(Integer classtime) {
		this.classtime = classtime;
	}
	
	@Column(name = "num")
	public Integer getNum() {
		return num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 19)
	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "state", nullable = false)
	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
