package com.jumper.entity;
// Generated 2016-4-7 16:37:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TOrder generated by hbm2java
 */
@Entity
@Table(name = "t_order", catalog = "lims")
public class TOrder implements java.io.Serializable {

	private int id;
	private int userId;
	private int facilityId;
	private int num;
	private Date lenddate;
	private int state;
	private String remark;

	public TOrder() {
	}

	public TOrder(int id, int userId, int facilityId, int num, Date lenddate, int state) {
		this.id = id;
		this.userId = userId;
		this.facilityId = facilityId;
		this.num = num;
		this.lenddate = lenddate;
		this.state = state;
	}

	public TOrder(int id, int userId, int facilityId, int num, Date lenddate, int state, String remark) {
		this.id = id;
		this.userId = userId;
		this.facilityId = facilityId;
		this.num = num;
		this.lenddate = lenddate;
		this.state = state;
		this.remark = remark;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "facility_id", nullable = false)
	public int getFacilityId() {
		return this.facilityId;
	}

	public void setFacilityId(int facilityId) {
		this.facilityId = facilityId;
	}

	@Column(name = "num", nullable = false)
	public int getNum() {
		return this.num;
	}

	public void setNum(int num) {
		this.num = num;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lenddate", nullable = false, length = 19)
	public Date getLenddate() {
		return this.lenddate;
	}

	public void setLenddate(Date lenddate) {
		this.lenddate = lenddate;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
