package com.jumper.entity;
// Generated 2016-4-7 16:37:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TRepairLog generated by hbm2java
 */
@Entity
@Table(name = "t_repair_log", catalog = "lims")
public class TRepairLog implements java.io.Serializable {

	private int id;
	private Integer facilityId;
	private String breakdownType;
	private Date breakdownDate;
	private Date repairDate;
	private String director;
	private String remark;
	private String reverse;

	public TRepairLog() {
	}

	public TRepairLog(int id) {
		this.id = id;
	}

	public TRepairLog(int id, Integer facilityId, String breakdownType, Date breakdownDate, Date repairDate,
			String director, String remark, String reverse) {
		this.id = id;
		this.facilityId = facilityId;
		this.breakdownType = breakdownType;
		this.breakdownDate = breakdownDate;
		this.repairDate = repairDate;
		this.director = director;
		this.remark = remark;
		this.reverse = reverse;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "facility_id")
	public Integer getFacilityId() {
		return this.facilityId;
	}

	public void setFacilityId(Integer facilityId) {
		this.facilityId = facilityId;
	}

	@Column(name = "breakdown_type")
	public String getBreakdownType() {
		return this.breakdownType;
	}

	public void setBreakdownType(String breakdownType) {
		this.breakdownType = breakdownType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "breakdown_date", length = 19)
	public Date getBreakdownDate() {
		return this.breakdownDate;
	}

	public void setBreakdownDate(Date breakdownDate) {
		this.breakdownDate = breakdownDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "repair_date", length = 19)
	public Date getRepairDate() {
		return this.repairDate;
	}

	public void setRepairDate(Date repairDate) {
		this.repairDate = repairDate;
	}

	@Column(name = "director")
	public String getDirector() {
		return this.director;
	}

	public void setDirector(String director) {
		this.director = director;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "reverse")
	public String getReverse() {
		return this.reverse;
	}

	public void setReverse(String reverse) {
		this.reverse = reverse;
	}

}
