package com.jumper.entity;
// Generated 2016-4-7 17:48:11 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TUser generated by hbm2java
 */
@Entity
@Table(name = "t_user", catalog = "lims")
public class TUser implements java.io.Serializable {

	private Integer id;
	private String userid;
	private String name;
	private String password;
	private byte authority;
	private String tel;
	private byte sex;
	private String department;
	private byte[] image;
	private Date createtime;
	private String reserve;

	public TUser() {
	}

	public TUser(String userid, String name, String password, byte authority, String tel, byte sex, Date createtime) {
		this.userid = userid;
		this.name = name;
		this.password = password;
		this.authority = authority;
		this.tel = tel;
		this.sex = sex;
		this.createtime = createtime;
	}

	public TUser(String userid, String name, String password, byte authority, String tel, byte sex, String department,
			byte[] image, Date createtime, String reserve) {
		this.userid = userid;
		this.name = name;
		this.password = password;
		this.authority = authority;
		this.tel = tel;
		this.sex = sex;
		this.department = department;
		this.image = image;
		this.createtime = createtime;
		this.reserve = reserve;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "userid", nullable = false, length = 20)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "password", nullable = false, length = 16)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "authority", nullable = false)
	public byte getAuthority() {
		return this.authority;
	}

	public void setAuthority(byte authority) {
		this.authority = authority;
	}

	@Column(name = "tel", nullable = false, length = 13)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "sex", nullable = false)
	public byte getSex() {
		return this.sex;
	}

	public void setSex(byte sex) {
		this.sex = sex;
	}

	@Column(name = "department")
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "image")
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createtime", nullable = false, length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Column(name = "reserve")
	public String getReserve() {
		return this.reserve;
	}

	public void setReserve(String reserve) {
		this.reserve = reserve;
	}

}
